development:
  adapter: postgresql
  database: cononrails_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: cononrails_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: cononrails_production
  pool: 5
  timeout: 5000